### PR TITLE
Fix for output path on linux

### PR DESCRIPTION
**Pull request by darklamp**
I guess the   "process.cwd()"   was there by mistake?

### CODE REVIEW

**Comment by sup3rgiu** [comment]
It's not, but need to "fix" this.

key path must be an absolute path, so through process.cwd() I get the working directory path.
However, if you use an absoulte path as `--outputDirectory` argument, this will cause an error.

I will fix it in the next commit check if `--outputDirectory` is an absolute path or not

**Comment by darklamp** [comment]
Sorry, I see. This should work.

**Comment by darklamp** [comment]
Please take a look. I should hopefully have fixed the absolute path problem; I've also added a quality flag, added  shorthand flags and fixed some english grammar.

**Comment by sup3rgiu** [comment]
Merged and fixed absolute path on Windows too with commit 97f47c84814cf6a00ba05b94f58eac31cea323da

Thanks!

**Pull request merged**
